version: '3'

services:
  apache:
    image: 'php:7.2-apache'
    container_name: php
    restart: always
    ports:
      - '8000:80'
    volumes:
      - ./public:/var/www/html
    depends_on:
      - mysqldb
    links:
      - mysqldb

  mysqldb:
    container_name: mysqlASW
    image: mysql:5.7
    restart: always
    ports:
      - '8080:80'
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=biblioteca